#pragma once

// generated by 3rdparty\sqlpp11\scripts\sqlite2cpp.py samples\sqlpp11_samples\sqlite3_insert\create.sql samples\sqlpp11_samples\sqlite3_insert\table table

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace table
{
  namespace TableToInsert_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
  } // namespace TableToInsert_

  struct TableToInsert: sqlpp::table_t<TableToInsert,
               TableToInsert_::Id>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "table_to_insert";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tableToInsert;
        T& operator()() { return tableToInsert; }
        const T& operator()() const { return tableToInsert; }
      };
    };
  };
  namespace TableSequence_
  {
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct Seq
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "seq";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T seq;
            T& operator()() { return seq; }
            const T& operator()() const { return seq; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null, sqlpp::tag::can_be_null>;
    };
  } // namespace TableSequence_

  struct TableSequence: sqlpp::table_t<TableSequence,
               TableSequence_::Name,
               TableSequence_::Seq>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "table_sequence";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tableSequence;
        T& operator()() { return tableSequence; }
        const T& operator()() const { return tableSequence; }
      };
    };
  };
} // namespace table
