# set(TensorRT_VERSION "7.2.3.4")
set(TensorRT_VERSION "8.6.1.6")
string(REPLACE "." ";" TensorRT_VERSION_LIST ${TensorRT_VERSION})
list(GET TensorRT_VERSION_LIST 0 TensorRT_VERSION_MAJOR)
list(GET TensorRT_VERSION_LIST 1 TensorRT_VERSION_MINOR)
list(GET TensorRT_VERSION_LIST 2 TensorRT_VERSION_PATCH)
add_definitions(-DTensorRT_VERSION_MAJOR=${TensorRT_VERSION_MAJOR})
if(WIN32)
    set(TensorRT_ROOT "D:/Software/dev/TensorRT-${TensorRT_VERSION}")
    set(TensorRT_INCLUDE_DIRS "${TensorRT_ROOT}/include")
    set(TensorRT_LIBRARY_DIR "${TensorRT_ROOT}/lib")
    find_library(NVINFER_LIB nvinfer HINTS ${TensorRT_LIBRARY_DIR})
    find_library(NVINFER_PLUGIN_LIB nvinfer_plugin HINTS ${TensorRT_LIBRARY_DIR})
    # find_library(MYELIN_LIB myelin64_1 HINTS ${TensorRT_LIBRARY_DIR})
    list(APPEND TensorRT_LIBS ${NVINFER_LIB} ${NVINFER_PLUGIN_LIB})
else()
    set(TensorRT_ROOT "D:/Software/dev/TensorRT-${TensorRT_VERSION}")
    set(TensorRT_INCLUDE_DIRS "${TensorRT_ROOT}/include")
    set(TensorRT_LIBRARY_DIR "${TensorRT_ROOT}/lib")
    find_library(NVINFER_LIB nvinfer HINTS ${TensorRT_LIBRARY_DIR} PATH_SUFFIXES lib64 lib/x64 lib)
    find_library(NVINFER_PLUGIN_LIB nvinfer_plugin HINTS ${TensorRT_LIBRARY_DIR} PATH_SUFFIXES lib64 lib/x64 lib)
    find_library(MYELIN_LIB myelin HINTS ${TensorRT_LIBRARY_DIR} PATH_SUFFIXES lib64 lib/x64 lib)
    list(APPEND TensorRT_LIBS ${MYELIN_LIB} ${NVINFER_LIB} ${NVINFER_PLUGIN_LIB})
endif()
