if (WIN32)
    set(TensorRT_ROOT E:/DevLib/TensorRT-7.2.3.4)
    set(TensorRT_INCLUDE_DIRS ${TensorRT_ROOT}/include)
    set(TensorRT_LIBRARY_DIRS ${TensorRT_ROOT}/lib)
    find_library(NVINFER_LIB nvinfer HINTS ${TensorRT_LIBRARY_DIRS})
    find_library(NVINFER_PLUGIN_LIB nvinfer_plugin HINTS ${TensorRT_LIBRARY_DIRS})
    find_library(MYELIN_LIB myelin64_1 HINTS ${TensorRT_LIBRARY_DIRS})
else()
    set(TensorRT_ROOT D:/Software/dev/TensorRT-7.2.3.4)
    set(TensorRT_INCLUDE_DIRS ${TensorRT_ROOT}/include)
    set(TensorRT_LIBRARY_DIRS ${TensorRT_ROOT}/lib)
    find_library(NVINFER_LIB nvinfer HINTS ${TensorRT_LIBRARY_DIRS} PATH_SUFFIXES lib64 lib/x64 lib)
    find_library(NVINFER_PLUGIN_LIB nvinfer_plugin HINTS ${TensorRT_LIBRARY_DIRS} PATH_SUFFIXES lib64 lib/x64 lib)
    find_library(MYELIN_LIB myelin HINTS ${TensorRT_LIBRARY_DIRS} PATH_SUFFIXES lib64 lib/x64 lib)
endif()

message(STATUS "TensorRT_ROOT ${TensorRT_ROOT}")
message(STATUS "TensorRT_INCLUDE_DIRS ${TensorRT_INCLUDE_DIRS}")
message(STATUS "TensorRT_LIBRARY_DIRS ${TensorRT_LIBRARY_DIRS}")
message(STATUS "NVINFER_LIB ${NVINFER_LIB}")
message(STATUS "NVINFER_PLUGIN_LIB ${NVINFER_PLUGIN_LIB}")
message(STATUS "MYELIN_LIB ${MYELIN_LIB}")
