message(STATUS "General configuration for free_kick-${PROJECT_VERSION}")
message(STATUS "")
message(STATUS "Build options")
message(STATUS "    CMAKE_INSTALL_PREFIX     : ${CMAKE_INSTALL_PREFIX}")

if(WARNINGS_AS_ERRORS)
    message(STATUS "    WARNINGS_AS_ERRORS       : ON")
else()
    message(STATUS "    WARNINGS_AS_ERRORS       : off")
endif()

if(ENABLE_COMPAT_OLD_GLIBC)
    message(STATUS "    ENABLE_COMPAT_OLD_GLIBC  : ON")
else()
    message(STATUS "    ENABLE_COMPAT_OLD_GLIBC  : off")
endif()

if(BUILD_TESTS)
    message(STATUS "    BUILD_TESTS              : ON")
else()
    message(STATUS "    BUILD_TESTS              : off")
endif()

if(BUILD_PYTHON)
    message(STATUS "    BUILD_PYTHON             : ON")
    message(STATUS "        Python versions : ${PYTHON_VERSIONS}")
else()
    message(STATUS "    BUILD_PYTHON             : off")
endif()

if(ENABLE_SANITIZER)
    message(STATUS "    ENABLE_SANITIZER         : ON")
else()
    message(STATUS "    ENABLE_SANITIZER         : off")
endif()

if(ENABLE_TEGRA)
    message(STATUS "    ENABLE_TEGRA             : ON")
else()
    message(STATUS "    ENABLE_TEGRA             : off")
endif()

message(STATUS "    Compilers used in public API header compatibility tests:")
if(PUBLIC_API_COMPILERS)
    foreach(comp ${PUBLIC_API_COMPILERS})
        string(MAKE_C_IDENTIFIER "${comp}" comp_str)
        string(TOUPPER "${comp_str}" COMP_STR)
        message(STATUS "        ${COMPILER_EXEC_${COMP_STR}}")
    endforeach()
else()
    message(STATUS "        (none)")
endif()

# Compilation

message(STATUS "")
message(STATUS "Platform")
message(STATUS "    Host             : ${CMAKE_HOST_SYSTEM_NAME} ${CMAKE_HOST_SYSTEM_VERSION} ${CMAKE_HOST_SYSTEM_PROCESSOR}")
message(STATUS "    Target           : ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION} ${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "    CMake            : ${CMAKE_VERSION}")
message(STATUS "    CMake generator  : ${CMAKE_GENERATOR}")
message(STATUS "    CMake build tool : ${CMAKE_BUILD_TOOL}")
message(STATUS "    Configuration    : ${CMAKE_BUILD_TYPE}")
message(STATUS "    ccache           : ${CCACHE_EXEC}")
message(STATUS "    ccache stats log : ${CCACHE_STATSLOG}")

message(STATUS "")

string(TOUPPER "${CMAKE_BUILD_TYPE}" BUILD_TYPE)
get_directory_property(dir_defs_ COMPILE_DEFINITIONS)
set(dir_defs "")
foreach(def ${dir_defs_})
    set(dir_defs "${dir_defs} -D${def}")
endforeach()
get_directory_property(dir_opt COMPILE_OPTIONS)

message(STATUS "Default compiler/linker config")
message(STATUS "    C++ Compiler : ${CMAKE_CXX_COMPILER} (${CMAKE_CXX_COMPILER_VERSION})")
message(STATUS "    C++ Standard : ${CMAKE_CXX_STANDARD}")
message(STATUS "    C++ Flags    : ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_${BUILD_TYPE}}")
message(STATUS "")
message(STATUS "    C Compiler   : ${CMAKE_C_COMPILER} (${CMAKE_C_COMPILER_VERSION})")
message(STATUS "    C Flags      : ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_${BUILD_TYPE}}")
message(STATUS "")
message(STATUS "    CUDA Compiler : ${CMAKE_CUDA_COMPILER} (${CMAKE_CUDA_COMPILER_VERSION})")
message(STATUS "    CUDA Arch     : ${CMAKE_CUDA_ARCHITECTURES}")
message(STATUS "    CUDA flags    : ${CMAKE_CUDA_FLAGS} ${CMAKE_CUDA_FLAGS_${BUILD_TYPE}}")
message(STATUS "    CUDA toolkit target dir : ${CUDAToolkit_TARGET_DIR}")
message(STATUS "")
message(STATUS "    Compiler Options    : ${dir_opt}")
message(STATUS "    Definitions         : ${dir_defs}")
message(STATUS "")
message(STATUS "    Linker flags (exec) : ${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_${BUILD_TYPE}}")
message(STATUS "    Linker flags (lib)  : ${CMAKE_SHARED_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_${BUILD_TYPE}}")
message(STATUS "")
message(STATUS "    Link-time optim.: supported ${LTO_SUPPORTED}, enabled ${LTO_ENABLED}")

message(STATUS "")
message(STATUS "OpenCV")
message(STATUS "    OpenCV version : ${OpenCV_VERSION}")
message(STATUS "    OpenCV build type : ")
message(STATUS "    OpenCV bin dir : ${OpenCV_BIN_DIR}")
message(STATUS "    OpenCV include dir : ${OpenCV_INCLUDE_DIRS}")
message(STATUS "    OpenCV lib dir : ${OpenCV_LIBRARY_DIR}")
message(STATUS "    OpenCV libs : ${OpenCV_LIBS}")

message(STATUS "")
message(STATUS "CUDA")
message(STATUS "    CUDAToolkit version : ${CUDAToolkit_VERSION}")
message(STATUS "    CUDAToolkit root : ${CUDAToolkit_TARGET_DIR}")
message(STATUS "    CUDAToolkit bin dir : ${CUDAToolkit_BIN_DIR}")
message(STATUS "    CUDAToolkit include dir: ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}")
message(STATUS "    CUDAToolkit include dir : ${CUDAToolkit_INCLUDE_DIRS}")
message(STATUS "    CUDAToolkit lib root : ${CUDAToolkit_LIBRARY_ROOT}")
message(STATUS "    CUDAToolkit lib dir : ${CUDAToolkit_LIBRARY_DIR}")
message(STATUS "    cudnn lib : ${CUDNN_LIB}")

message(STATUS "")
message(STATUS "TensorRT")
message(STATUS "    TensorRT version : ${TensorRT_VERSION}")
message(STATUS "    TensorRT root : ${TensorRT_ROOT}")
message(STATUS "    TensorRT bin dir : ${TensorRT_BIN_DIR}")
message(STATUS "    TensorRT include dir : ${TensorRT_INCLUDE_DIRS}")
message(STATUS "    TensorRT lib dir : ${TensorRT_LIBRARY_DIR}")
message(STATUS "    TensorRT libs : ${TensorRT_LIBS}")

